# Generated by Django 5.0 on 2024-01-02 22:06

import admin.models.admin
import admin.models.session
import django.db.models.deletion
import utils.web.fields.pd_datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUserModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_name', models.CharField(max_length=50, verbose_name='key name')),
                ('auth_token', models.CharField(db_index=True, default=admin.models.admin.get_new_auth_token, max_length=100, verbose_name='auth token')),
                ('created_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'admin_user',
            },
        ),
        migrations.CreateModel(
            name='AdminSessionModel',
            fields=[
                ('session_key', models.CharField(default=admin.models.session.get_new_session_key, max_length=100, primary_key=True, serialize=False, verbose_name='session key')),
                ('csrf_token', models.CharField(max_length=16, null=True, verbose_name='csrf token')),
                ('updated_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now=True)),
                ('created_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='admin.adminusermodel')),
            ],
            options={
                'db_table': 'admin_session',
            },
        ),
    ]
