# Generated by Django 5.0 on 2024-01-02 22:06

import django.db.models.deletion
import mobile.models.session
import utils.web.fields.pd_datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cdn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileQuizAnswerModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'mobile_quiz_answer',
            },
        ),
        migrations.CreateModel(
            name='MobileFoodCategoryModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdn.filestoremodel')),
                ('parent', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='mobile.mobilefoodcategorymodel')),
            ],
            options={
                'db_table': 'mobile_food_category',
            },
        ),
        migrations.CreateModel(
            name='MobileFoodModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.JSONField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='mobile.mobilefoodcategorymodel')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdn.filestoremodel')),
            ],
            options={
                'db_table': 'mobile_food',
            },
        ),
        migrations.CreateModel(
            name='MobileNewsModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('content', models.JSONField(null=True)),
                ('created_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_images', to='cdn.filestoremodel')),
            ],
            options={
                'db_table': 'mobile_news',
            },
        ),
        migrations.CreateModel(
            name='MobileQuizModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passing_percentage', models.IntegerField(default=100)),
                ('name', models.CharField(max_length=100)),
                ('content', models.JSONField(null=True)),
                ('newbie_required', models.BooleanField(default=False)),
                ('created_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now_add=True)),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdn.filestoremodel')),
            ],
            options={
                'db_table': 'mobile_quiz',
            },
        ),
        migrations.CreateModel(
            name='MobileQuizQuestionModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('type', models.CharField(choices=[('option', 'Option'), ('text', 'Text')], default='text', max_length=20)),
                ('created_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now_add=True)),
                ('correct_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mobile.mobilequizanswermodel')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdn.filestoremodel')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mobile.mobilequizmodel')),
            ],
            options={
                'db_table': 'mobile_quiz_question',
            },
        ),
        migrations.AddField(
            model_name='mobilequizanswermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mobile.mobilequizquestionmodel'),
        ),
        migrations.CreateModel(
            name='MobileQuizUserSprintModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('while_taking', 'While Taking'), ('on_verification', 'On Verification'), ('correct', 'Correct'), ('incorrect', 'Incorrent')], default='while_taking', max_length=20)),
                ('finished_at', utils.web.fields.pd_datetime.PendulumDateTimeField(null=True)),
                ('created_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sprints', to='mobile.mobilequizmodel')),
            ],
            options={
                'db_table': 'mobile_quiz_user_sprint',
            },
        ),
        migrations.CreateModel(
            name='MobileQuizUserAnswerModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('on_verification', 'On Verification'), ('incorrect', 'Incorrent'), ('correct', 'Correct')], default='on_verification', max_length=20)),
                ('text_answer', models.TextField(max_length=1000, null=True)),
                ('updated_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now=True)),
                ('option_answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mobile.mobilequizanswermodel')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='mobile.mobilequizquestionmodel')),
                ('sprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='mobile.mobilequizusersprintmodel')),
            ],
            options={
                'db_table': 'mobile_quiz_user_answer',
            },
        ),
        migrations.CreateModel(
            name='MobileUserModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('status', models.CharField(choices=[('newbie', 'Newbie'), ('active', 'Active'), ('leave', 'Leave')], default='newbie', max_length=20)),
                ('password_hash', models.CharField(max_length=1000)),
                ('birthday', utils.web.fields.pd_datetime.PendulumDateField()),
                ('working_at', utils.web.fields.pd_datetime.PendulumDateField(auto_now_add=True)),
                ('updated_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now=True)),
                ('created_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now_add=True)),
                ('avatar', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cdn.filestoremodel')),
            ],
            options={
                'db_table': 'mobile_user',
            },
        ),
        migrations.CreateModel(
            name='MobileSessionModel',
            fields=[
                ('auth_token', models.CharField(db_index=True, default=mobile.models.session.get_new_auth_token, max_length=120, primary_key=True, serialize=False)),
                ('fcm_token', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], max_length=15)),
                ('extra', models.JSONField(null=True)),
                ('updated_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now=True)),
                ('created_at', utils.web.fields.pd_datetime.PendulumDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='mobile.mobileusermodel')),
            ],
            options={
                'db_table': 'mobile_session',
            },
        ),
        migrations.AddField(
            model_name='mobilequizusersprintmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_sprints', to='mobile.mobileusermodel'),
        ),
    ]
