# Generated by Django 5.0 on 2024-01-02 22:06

import cdn.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileStoreModel',
            fields=[
                ('uuid', models.CharField(default=cdn.models.get_new_uuid, editable=False, max_length=200, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(choices=[('file', 'File'), ('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('recycle', models.BooleanField(default=False)),
                ('checked_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'file_store',
            },
        ),
    ]
